// This file will be auto-generated by Supabase CLI
// For now, we'll define the basic types manually
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > types/database.ts
// to generate types from your actual database schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string;
          display_name: string | null;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          username: string;
          display_name?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          username?: string;
          display_name?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      maps: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          subtitle: string | null;
          config: Json;
          is_published: boolean;
          thumbnail_url: string | null;
          vote_score: number;
          published_at: string | null;
          created_at: string;
          updated_at: string;
          // Sculpture-related fields (Phase 4.6)
          product_type: 'poster' | 'sculpture';
          sculpture_config: Json | null;
          sculpture_thumbnail_url: string | null;
          // Remix tracking fields (Phase 8)
          remixed_from_id: string | null;
          remix_count: number;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          subtitle?: string | null;
          config: Json;
          is_published?: boolean;
          thumbnail_url?: string | null;
          vote_score?: number;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
          // Sculpture-related fields (Phase 4.6)
          product_type?: 'poster' | 'sculpture';
          sculpture_config?: Json | null;
          sculpture_thumbnail_url?: string | null;
          // Remix tracking fields (Phase 8)
          remixed_from_id?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          subtitle?: string | null;
          config?: Json;
          is_published?: boolean;
          thumbnail_url?: string | null;
          vote_score?: number;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
          // Sculpture-related fields (Phase 4.6)
          product_type?: 'poster' | 'sculpture';
          sculpture_config?: Json | null;
          sculpture_thumbnail_url?: string | null;
          // Remix tracking fields (Phase 8)
          remixed_from_id?: string | null;
        };
      };
      votes: {
        Row: {
          id: string;
          user_id: string;
          map_id: string;
          value: number; // -1 or 1
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          map_id: string;
          value: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          map_id?: string;
          value?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      comments: {
        Row: {
          id: string;
          user_id: string;
          map_id: string;
          content: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          map_id: string;
          content: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          map_id?: string;
          content?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      rate_limits: {
        Row: {
          user_id: string;
          action_type: string;
          request_timestamps: Json;
          window_start: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          action_type: string;
          request_timestamps?: Json;
          window_start?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          action_type?: string;
          request_timestamps?: Json;
          window_start?: string;
          updated_at?: string;
        };
      };
      api_usage: {
        Row: {
          id: string;
          source: string; // 'maptiler', 'openfreemap', etc.
          date: string; // YYYY-MM-DD
          request_count: number;
          tilejson_count: number; // TileJSON requests (counted separately)
          error_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          source: string;
          date: string;
          request_count?: number;
          tilejson_count?: number;
          error_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          source?: string;
          date?: string;
          request_count?: number;
          tilejson_count?: number;
          error_count?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}

